include:
  file: bookworm-minbase.yaml

device:
  layer: rpi5
  user1: vti
  user1pass: Fo0bar!!
  hostname: bicycledatatest

image:
  layer: image-rpios
  boot_part_size: 128M
  root_part_size: 1536M
  name: bicycledata

locale:
  default: sv_SE.UTF-8
  timezone: Europe/Stockholm
  keyboard_keymap: se
  keyboard_layout: Swedish

ssh:
  pubkey_only: n

packages:
  - wpasupplicant
  - git
  - btop
  - curl

env:
  SSID: bicycledata
  PSK: bicycledata

layer:
  base: bookworm-minbase
  custom: bicycledata-service
