device:
  layer: pi5
  user1: vti
  user1pass: Fo0bar!!
  hostname: bicycledata

image:
  layer: image-rpios
  boot_part_size: 128M
  root_part_size: 1536M
  name: bicycledata

ssh:
  pubkey_only: n

packages:
  - wpasupplicant
  - git
  - btop

env:
  SSID: bicycledata
  PSK: bicycledata

layer:
  custom: bicycledata-service
