include:
  file: bookworm-minbase.yaml

device:
  layer: rpi5
  hostname: bicycledata
  user1: vti
  user1pass: Fo0bar!!

image:
  layer: image-rpios
  boot_part_size: 200%
  root_part_size: 300%
  name: bicycledata

layer:
  custom: bicycledata-packages
  custom: bicycledata-service
  custom: bicycledata-locale
